import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  coverPage: { padding: 40, fontFamily: "Helvetica", justifyContent: "center", alignItems: "center" },
  title: { fontSize: 28, fontWeight: "bold", marginBottom: 8 },
  subtitle: { fontSize: 14, color: "#888", marginBottom: 4 },
  sectionTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 8, marginTop: 16 },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#eee", paddingVertical: 4 },
  headerRow: { flexDirection: "row", borderBottomWidth: 2, borderBottomColor: "#333", paddingVertical: 4, marginBottom: 2 },
  cell: { flex: 1, fontSize: 9 },
  headerCell: { flex: 1, fontSize: 9, fontWeight: "bold" },
  statBox: { padding: 8, marginBottom: 8, backgroundColor: "#f5f5f5", borderRadius: 4 },
  statLabel: { fontSize: 8, color: "#888" },
  statValue: { fontSize: 18, fontWeight: "bold" },
  footer: { position: "absolute", bottom: 20, left: 40, right: 40, fontSize: 8, color: "#aaa", textAlign: "center" },
});

export interface ReportData {
  userName: string;
  startDate: string;
  endDate: string;
  summary: {
    workoutsCompleted: number;
    totalVolume: number;
    totalSets: number;
    avgDailyCalories: number;
    weightChange: string;
    prsHit: number;
  };
  workoutLog: { date: string; split: string; exercise: string; topSet: string }[];
  nutritionAvg: { calories: number; protein: number; carbs: number; fats: number };
  nutritionTargets: { calories: number; protein: number; carbs: number; fats: number };
  weightData: { date: string; weight: number }[];
  fastingAdherence: { percentage: number; streak: number; protocol: string };
  goals: { title: string; type: string; progress: number; status: string }[];
}

export function ProgressReport({ data }: { data: ReportData }) {
  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.coverPage}>
        <Text style={styles.title}>BuffNStuff</Text>
        <Text style={styles.subtitle}>Progress Report</Text>
        <Text style={{ fontSize: 12, marginTop: 16 }}>
          {data.startDate} — {data.endDate}
        </Text>
        {data.userName && (
          <Text style={{ fontSize: 12, marginTop: 8, color: "#666" }}>{data.userName}</Text>
        )}
      </Page>

      {/* Summary + Workout Log */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Summary</Text>
        <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>
          {[
            { label: "Workouts", value: data.summary.workoutsCompleted.toString() },
            { label: "Total Volume", value: `${data.summary.totalVolume.toLocaleString()} lbs` },
            { label: "Total Sets", value: data.summary.totalSets.toString() },
            { label: "Avg Daily Cal", value: data.summary.avgDailyCalories.toString() },
            { label: "Weight Change", value: data.summary.weightChange },
            { label: "PRs Hit", value: data.summary.prsHit.toString() },
          ].map((stat) => (
            <View key={stat.label} style={[styles.statBox, { width: "30%" }]}>
              <Text style={styles.statLabel}>{stat.label}</Text>
              <Text style={styles.statValue}>{stat.value}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.sectionTitle}>Workout Log</Text>
        <View style={styles.headerRow}>
          <Text style={styles.headerCell}>Date</Text>
          <Text style={styles.headerCell}>Split</Text>
          <Text style={styles.headerCell}>Exercise</Text>
          <Text style={styles.headerCell}>Top Set</Text>
        </View>
        {data.workoutLog.slice(0, 40).map((row, i) => (
          <View key={i} style={styles.row}>
            <Text style={styles.cell}>{row.date}</Text>
            <Text style={styles.cell}>{row.split}</Text>
            <Text style={styles.cell}>{row.exercise}</Text>
            <Text style={styles.cell}>{row.topSet}</Text>
          </View>
        ))}
        <Text style={styles.footer}>Generated by BuffNStuff</Text>
      </Page>

      {/* Nutrition + Weight + Fasting + Goals */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Nutrition Overview</Text>
        <View style={{ flexDirection: "row", gap: 8 }}>
          {["Calories", "Protein (g)", "Carbs (g)", "Fats (g)"].map((label, i) => {
            const keys = ["calories", "protein", "carbs", "fats"] as const;
            const actual = data.nutritionAvg[keys[i]];
            const target = data.nutritionTargets[keys[i]];
            return (
              <View key={label} style={[styles.statBox, { width: "23%" }]}>
                <Text style={styles.statLabel}>{label}</Text>
                <Text style={styles.statValue}>{actual}</Text>
                <Text style={{ fontSize: 8, color: "#888" }}>Target: {target}</Text>
              </View>
            );
          })}
        </View>

        <Text style={styles.sectionTitle}>Weight Trend</Text>
        <View style={styles.headerRow}>
          <Text style={styles.headerCell}>Date</Text>
          <Text style={styles.headerCell}>Weight</Text>
        </View>
        {data.weightData.slice(0, 30).map((row, i) => (
          <View key={i} style={styles.row}>
            <Text style={styles.cell}>{row.date}</Text>
            <Text style={styles.cell}>{row.weight}</Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>Fasting Adherence</Text>
        <View style={styles.statBox}>
          <Text style={{ fontSize: 12 }}>
            Protocol: {data.fastingAdherence.protocol} | Adherence: {data.fastingAdherence.percentage}% | Streak: {data.fastingAdherence.streak} days
          </Text>
        </View>

        <Text style={styles.sectionTitle}>Goals</Text>
        {data.goals.map((goal, i) => (
          <View key={i} style={{ marginBottom: 6 }}>
            <Text style={{ fontWeight: "bold", fontSize: 10 }}>
              {goal.title} ({goal.status})
            </Text>
            <Text style={{ fontSize: 9, color: "#666" }}>
              {goal.type} — {goal.progress}% complete
            </Text>
          </View>
        ))}
        <Text style={styles.footer}>Generated by BuffNStuff</Text>
      </Page>
    </Document>
  );
}
